name: CI

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    # All commands run inside lumen-api/
    defaults:
      run:
        working-directory: lumen-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, pdo_sqlite, sqlite, tokenizer, dom, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: lumen-api/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('lumen-api/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare SQLite DB file
        run: |
          mkdir -p database
          : > database/testing.sqlite
          ls -lah database

      # Write BOTH .env and .env.testing to be extra explicit
      - name: Write .env and .env.testing (SQLite + array cache)
        run: |
          for f in .env .env.testing; do
          cat > "$f" << 'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_NAME=energeX-api

          DB_CONNECTION=sqlite
          DB_DATABASE=database/testing.sqlite

          CACHE_DRIVER=array
          QUEUE_CONNECTION=sync

          JWT_SECRET=ci-secret
          JWT_TTL=3600
          JWT_ISS=energeX-api
          JWT_AUD=energeX-clients
          JWT_LEEWAY=60
          EOF
          done
          echo "----- .env -----"
          cat .env
          echo "----- .env.testing -----"
          cat .env.testing

      # Some projects pin DB settings in phpunit.xml; pass env here to override
      - name: Run PHPUnit
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
          JWT_SECRET: ci-secret
        run: php vendor/bin/phpunit --colors=always
