name: CI

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lumen-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, pdo_sqlite, sqlite, tokenizer, dom, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: lumen-api/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('lumen-api/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare SQLite for tests
        run: |
          mkdir -p database
          : > database/testing.sqlite

      - name: Write .env for CI (SQLite + array cache)
        run: |
          cat > .env << 'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_NAME=energeX-api

          DB_CONNECTION=sqlite
          DB_DATABASE=database/testing.sqlite

          CACHE_DRIVER=array
          QUEUE_CONNECTION=sync

          JWT_SECRET=ci-secret
          JWT_TTL=3600
          JWT_ISS=energeX-api
          JWT_AUD=energeX-clients
          JWT_LEEWAY=60
          EOF

      - name: Run PHPUnit
        env:
          APP_ENV: testing
        run: php vendor/bin/phpunit --colors=always
