name: CI

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energex_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, tokenizer, dom, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer deps
        working-directory: lumen-api
        run: composer install --no-interaction --prefer-dist --no-progress

      # Use a CI-specific env so tests don’t depend on Redis, etc.
      - name: Write .env for CI
        run: |
          cat > .env << 'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_NAME=energeX-api

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=energeX_test
          DB_USERNAME=root
          DB_PASSWORD=root

          # Keep tests simple & fast: in-memory cache
          CACHE_DRIVER=array

          # JWT (any non-empty secret)
          JWT_SECRET=ci-secret
          JWT_TTL=3600
          JWT_ISS=energeX-api
          JWT_AUD=energeX-clients
          JWT_LEEWAY=60
          EOF

      - name: Wait for MySQL
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 -proot --silent; do
            echo "Waiting for MySQL…"
            sleep 2
          done

      # If your migrations are needed outside tests, uncomment:
      # - name: Migrate
      #   run: php artisan migrate --force

      - name: Run PHPUnit
        working-directory: lumen-api
        run: php vendor/bin/phpunit --colors=always
