name: CI

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energex_test   # <-- lower-case, matches .env below
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    # Run all shell steps from lumen-api/
    defaults:
      run:
        working-directory: lumen-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, pdo_mysql, tokenizer, dom, fileinfo
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: lumen-api/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('lumen-api/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Write .env for CI (MySQL)
        run: |
          cat > .env << 'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_NAME=energeX-api

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=energex_test
          DB_USERNAME=root
          DB_PASSWORD=root

          CACHE_DRIVER=array
          QUEUE_CONNECTION=sync

          JWT_SECRET=ci-secret
          JWT_TTL=3600
          JWT_ISS=energeX-api
          JWT_AUD=energeX-clients
          JWT_LEEWAY=60
          EOF
          echo "Wrote lumen-api/.env"

      - name: Wait for MySQL (healthy & accepting connections)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client
          echo "Waiting for MySQL healthcheck..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "MySQL not ready yet... ($i)"
            sleep 2
          done
          echo "Showing databases (should include energex_test):"
          mysql -h 127.0.0.1 -uroot -proot -e 'SHOW DATABASES;'

      # If your tests use DatabaseMigrations (migrate:fresh), you don't need a manual migrate.
      # Uncomment the next step only if migrations are required prior to tests for seeding, etc.
      # - name: Run migrations
      #   run: php artisan migrate --force

      - name: Run PHPUnit
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: energex_test
          DB_USERNAME: root
          DB_PASSWORD: root
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
          JWT_SECRET: ci-secret
        run: php vendor/bin/phpunit --colors=always
